/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: bd209cac-aafb-4825-bd93-c5266bd62f81

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of the Prime Inertia Engine v2.0.

We have defined the `ThetaKernel` and the `HasPrimeInertia` property (modular weight 1/2).
We defined the `PrimeInertia_L_Function` via the Mellin transform.
We investigated the `PrimeInertia_Generates_Symmetry` claim and found it to be false as stated, because the integral definition diverges for Re(s) <= 1 (specifically at s = -1), while the symmetry would imply equality with a convergent value at s = 2. We proved this negation in `PrimeInertia_Generates_Symmetry_False`.
We defined `HermitianOperator` and the `PrimeInertia_Spectral_Correspondence` property.
We proved `Vacuum_Stability_Guaranteed`, showing that if the spectral correspondence holds, the Riemann Hypothesis follows (zeros have real part 1/2).
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Complex Real MeasureTheory Set Filter UpperHalfPlane

def ThetaKernel := ℂ → ℂ

/-
The "Prime Inertia" Condition (Modular Weight 1/2). The kernel must transform under S : τ → -1/τ with a specific factor.
-/
def HasPrimeInertia (θ : ThetaKernel) : Prop :=
  ∀ (τ : ℂ), 0 < τ.im → θ (-1 / τ) = ((τ / Complex.I) ^ (1 / 2 : ℂ)) * θ τ

/-
The classic Jacobi Theta function is the standard model for this kernel. We posit that the physical vacuum behaves like this series.
-/
def JacobiThetaSum (τ : ℂ) : ℂ :=
  ∑' (n : ℤ), cexp (Real.pi * Complex.I * n ^ 2 * τ)

/-
The Mellin Transform definition for our specific Prime Inertia Engine. We integrate from 0 to infinity.
-/
def PrimeInertia_L_Function (θ : ThetaKernel) (s : ℂ) : ℂ :=
  ∫ (y : ℝ) in Ioi 0, (θ (Complex.I * y) - 1) * (y : ℂ) ^ (s / 2 - 1)

/-
A symmetric form of the L-function, derived by splitting the integral and applying the functional equation.
-/
def Symmetric_L_Form (θ : ThetaKernel) (s : ℂ) : ℂ :=
  (∫ (y : ℝ) in Ioi 1, (θ (Complex.I * y) - 1) * (y ^ (s / 2 - 1) + y ^ ((1 - s) / 2 - 1))) - (2 / s + 2 / (1 - s))

/-
Define a Hermitian Operator abstractly.
-/
structure HermitianOperator (H : Type) [NormedAddCommGroup H] [InnerProductSpace ℂ H] where
  op : H →L[ℂ] H
  is_hermitian : ∀ x y, inner ℂ (op x) y = inner ℂ x (op y)

/-
AXIOM: The zeros of the L-function correspond to eigenvalues of this operator. This is the "Spectral Interpretation" of the Riemann Zeros.
-/
def PrimeInertia_Spectral_Correspondence
  (θ : ThetaKernel) (H : Type) [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  (Op : HermitianOperator H) : Prop :=
  ∀ (ρ : ℂ), PrimeInertia_L_Function θ ρ = 0 → ∃ (E : ℝ), ρ = 1/2 + Complex.I * E

/-
If the Spectral Correspondence holds, the Vacuum is stable (zeros are on 1/2).
-/
theorem Vacuum_Stability_Guaranteed
  (θ : ThetaKernel) (H : Type) [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  (Op : HermitianOperator H)
  (h_spectral : PrimeInertia_Spectral_Correspondence θ H Op) :
  ∀ (ρ : ℂ), PrimeInertia_L_Function θ ρ = 0 → ρ.re = 1/2 := by
  intro ρ h_zero
  have h_exists := h_spectral ρ h_zero
  rcases h_exists with ⟨E, h_eq⟩
  rw [h_eq]
  simp

/-
The L-function at s = -1 is 0 because the integral diverges.
-/
lemma PrimeInertia_L_Function_divergence_at_neg_one
  (θ : ThetaKernel) (h_inertia : HasPrimeInertia θ)
  (h_lim : Filter.Tendsto (fun y : ℝ => θ (Complex.I * y)) Filter.atTop (nhds 1))
  (h_pos : ∀ y : ℝ, 0 < y → 0 < (θ (Complex.I * y)).re) :
  PrimeInertia_L_Function θ (-1) = 0 := by
  refine' MeasureTheory.integral_undef _;
  intro hy; have := hy.norm; norm_num [ Complex.normSq, Complex.norm_def ] at this;
  -- For $y$ near $0$, we have $|\theta(iy) - 1| \geq \frac{1}{2}$.
  have h_bound : ∃ ε > 0, ∀ y : ℝ, 0 < y ∧ y < ε → Real.sqrt (((θ (Complex.I * y)).re - 1) * ((θ (Complex.I * y)).re - 1) + (θ (Complex.I * y)).im * (θ (Complex.I * y)).im) ≥ 1 / 2 := by
    -- Using the functional equation, we have $\theta(iy) = y^{-1/2} \theta(i/y)$.
    have h_fun_eq : ∀ y : ℝ, 0 < y → θ (Complex.I * y) = y^(-1 / 2 : ℂ) * θ (Complex.I / y) := by
      intro y hy; specialize h_inertia ( Complex.I / y ) ; simp_all +decide [ div_eq_mul_inv, Complex.cpow_neg ] ;
      convert h_inertia using 1 <;> ring ; norm_num [ hy.ne' ];
      rw [ mul_comm, Complex.inv_cpow ];
      rw [ Complex.arg_ofReal_of_nonneg hy.le ] ; linarith [ Real.pi_pos ];
    -- As $y \to 0$, $\theta(i/y) \to 1$, so $\theta(iy) \sim y^{-1/2}$.
    have h_theta_iy : Filter.Tendsto (fun y : ℝ => (θ (Complex.I * y)).re * y^(1 / 2 : ℝ)) (nhdsWithin 0 (Set.Ioi 0)) (nhds 1) := by
      have h_theta_iy : Filter.Tendsto (fun y : ℝ => (θ (Complex.I / y)).re) (nhdsWithin 0 (Set.Ioi 0)) (nhds 1) := by
        convert Complex.continuous_re.continuousAt.tendsto.comp ( h_lim.comp tendsto_inv_nhdsGT_zero ) using 2 ; norm_num [ div_eq_mul_inv ];
      refine' Filter.Tendsto.congr' _ h_theta_iy;
      filter_upwards [ self_mem_nhdsWithin ] with y hy ; rw [ h_fun_eq y hy ] ; norm_num [ Complex.exp_re, Complex.exp_im, Complex.log_re, Complex.log_im, Complex.cpow_def ] ; ring;
      norm_num [ Complex.exp_re, Complex.exp_im, Complex.log_re, Complex.log_im, hy.out.ne', Real.rpow_def_of_pos hy.out ] ; ring;
      norm_num [ Complex.arg_ofReal_of_nonneg hy.out.le, mul_assoc, mul_left_comm, ← Real.exp_add ];
    have := Metric.tendsto_nhdsWithin_nhds.mp h_theta_iy ( 1 / 4 ) ( by norm_num ) ; norm_num at this;
    obtain ⟨ δ, hδ₁, hδ₂ ⟩ := this; use Min.min δ ( 1 / 4 ) ; norm_num [ hδ₁ ];
    intro y hy₁ hy₂ hy₃; specialize hδ₂ hy₁ ( abs_lt.mpr ⟨ by linarith, by linarith ⟩ ) ; norm_num [ Real.dist_eq ] at hδ₂;
    rw [ abs_lt ] at hδ₂;
    rw [ ← Real.sqrt_sq ( le_of_lt ( h_pos y hy₁ ) ) ] at *;
    norm_num [ ← Real.sqrt_eq_rpow ] at *;
    field_simp;
    rw [ Real.sqrt_sq ( le_of_lt ( h_pos y hy₁ ) ) ] at *;
    nlinarith [ show 0 < Real.sqrt y by positivity, show Real.sqrt y < 1 / 2 by rw [ Real.sqrt_lt' ] <;> linarith, Real.mul_self_sqrt ( show 0 ≤ y by positivity ), Real.sqrt_nonneg ( ( ( θ ( Complex.I * y ) |> Complex.re ) - 1 ) ^ 2 + ( θ ( Complex.I * y ) |> Complex.im ) ^ 2 ), Real.mul_self_sqrt ( show 0 ≤ ( ( θ ( Complex.I * y ) |> Complex.re ) - 1 ) ^ 2 + ( θ ( Complex.I * y ) |> Complex.im ) ^ 2 by positivity ) ];
  -- Using the bound, we can show that the integral of $|\theta(iy) - 1| * y^{-3/2}$ over $(0, \epsilon)$ diverges.
  obtain ⟨ε, hε_pos, hε_bound⟩ := h_bound;
  have h_integral_diverges : ¬ MeasureTheory.IntegrableOn (fun y : ℝ => (1 / 2) * y ^ (-3 / 2 : ℝ)) (Set.Ioo 0 ε) := by
    have h_integral_diverges : ¬ MeasureTheory.IntegrableOn (fun y : ℝ => y ^ (-3 / 2 : ℝ)) (Set.Ioo 0 ε) := by
      rw [ ← intervalIntegrable_iff_integrableOn_Ioo_of_le hε_pos.le ] ; rw [ intervalIntegrable_iff_integrableOn_Ioc_of_le hε_pos.le ] ; rw [ integrableOn_Ioc_iff_integrableOn_Ioo ] ; rw [ intervalIntegral.integrableOn_Ioo_rpow_iff ] <;> norm_num ; linarith;
    exact fun h => h_integral_diverges <| by simpa [ MeasureTheory.IntegrableOn ] using h.const_mul 2;
  have h_integral_diverges : ¬ MeasureTheory.IntegrableOn (fun y : ℝ => Real.sqrt (((θ (Complex.I * y)).re - 1) * ((θ (Complex.I * y)).re - 1) + (θ (Complex.I * y)).im * (θ (Complex.I * y)).im) * y ^ (-3 / 2 : ℝ)) (Set.Ioo 0 ε) := by
    refine fun h => h_integral_diverges <| h.mono' ?_ ?_;
    · exact Measurable.aestronglyMeasurable ( by exact measurable_const.mul ( measurable_id.pow_const _ ) );
    · filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Ioo ] with y hy using by rw [ Real.norm_of_nonneg ( mul_nonneg ( by norm_num ) ( Real.rpow_nonneg hy.1.le _ ) ) ] ; exact mul_le_mul_of_nonneg_right ( hε_bound y hy ) ( Real.rpow_nonneg hy.1.le _ ) ;
  refine h_integral_diverges <| this.mono_measure ( MeasureTheory.Measure.restrict_mono ( Set.Ioo_subset_Ioi_self ) le_rfl ) |> fun h => h.congr ?_;
  filter_upwards [ MeasureTheory.ae_restrict_mem measurableSet_Ioo ] with y hy;
  norm_num [ Complex.exp_re, Complex.exp_im, Complex.log_re, Complex.log_im, Complex.cpow_def_of_ne_zero, hy.1.ne' ];
  norm_num [ Complex.arg_ofReal_of_nonneg hy.1.le ] ; ring_nf ; norm_num [ Real.exp_neg, Real.exp_mul, Real.exp_log hy.1 ];
  exact Or.inl ( by rw [ Real.sqrt_sq ( by exact Real.rpow_nonneg hy.1.le _ ), Real.rpow_neg hy.1.le ] )

#check nhds

/-
The L-function as defined (via integral) is not symmetric because the integral diverges for Re(s) <= 1, while the symmetry would map these to convergent values.
-/
theorem PrimeInertia_Generates_Symmetry_False
  (θ : ThetaKernel) (h_inertia : HasPrimeInertia θ)
  (h_lim : Filter.Tendsto (fun y : ℝ => θ (Complex.I * y)) Filter.atTop (nhds 1))
  (h_pos : ∀ y : ℝ, 0 < y → 0 < (θ (Complex.I * y)).re - 1)
  (h_L2_ne_zero : PrimeInertia_L_Function θ 2 ≠ 0) :
  ¬ (∀ (s : ℂ), s ≠ 0 → s ≠ 1 → PrimeInertia_L_Function θ s = PrimeInertia_L_Function θ (1 - s)) := by
  intro h_symm
  have h_neg_one : PrimeInertia_L_Function θ (-1) = 0 := by
    apply PrimeInertia_L_Function_divergence_at_neg_one θ h_inertia h_lim
    intro y hy
    specialize h_pos y hy
    linarith
  have h_contra : PrimeInertia_L_Function θ (-1) = PrimeInertia_L_Function θ 2 := by
    convert h_symm (-1) (by norm_num) (by norm_num) using 2
    norm_num
  rw [h_neg_one] at h_contra
  rw [← h_contra] at h_L2_ne_zero
  contradiction
